# This is a basic workflow to help you get started with Actions

name: Run bot

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "user_interface.py"
  schedule:
    - cron: "1 */5 * * *"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v4.1.0

      - name: Injection For my Repo
        run: sed -i "s/TokenTimeIsBackBuddyss/${{ secrets.LICHESS_KEY }}/g" config.yml

      - name: Stockfish
        run: |
          chmod +x ./engines/stockfish

      - name: Running the bot
        run: python user_interface.py
